name: Composite action greeter
description: Used to greet people B)
inputs:
  who-to-greet:
    description: who are we greeting
    required: true
    default: World
outputs:
  random-number:
    description: Lotto results
    value: ${{ steps.number-generator.outputs.random-number }}
runs:
  using: 'composite'
  steps:
    - name: Say hello in powershell core
      shell: pwsh
      run: Write-Output "Hello ${{ inputs.who-to-greet }}"
    
    - name: Generate lucky number
      id: number-generator
      shell: bash
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT

    - name: Say goodbye in python
      shell: python
      run: python3 -c "print('Goodbye, the lucky number for today is ${{ job.outputs.random-number }}')"
      
