name: Action 1
on: 
  pull_request:
    types: [opened, closed]
jobs:
  pr_opened:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - uses: actions/checkout@v3
      
      - name: "Add greeting comment"
        run: gh pr comment ${{ github.event.number }} --body "Good day"
        
  pr_closed:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Save goodbye message to environment variable
        run:  | 
          export GOODBYE=$(cat goodbye.txt)
          printenv
          
      - name: Comment goodbye using message saved in environment variable using GitHub script
        uses: actions/github-script@v6
        with:
          script: |
            VALUE=${{ env.GOODBYE }}
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: $VALUE
            })
            
        
        
        
        
      
