name: Action 4
on:
  workflow_dispatch:
    inputs:
      context-github:
        description: 'Include github context'
        type: boolean
        default: true
        
      context-env:
        description: 'Include env context'
        type: boolean
        default: true
        
      context-job:
        description: 'Include job context'
        type: boolean
        default: true
        
      context-steps:
        description: 'Include steps context'
        type: boolean
        default: true
        
      context-runner:
        description: 'Include runner context'
        type: boolean
        default: true
        
      context-secrets:
        description: 'Include secrets context'
        type: boolean
        default: true
        
      context-strategy:
        description: 'Include strategy context'
        type: boolean
        default: true
        
      context-matrix:
        description: 'Include matrix context'
        type: boolean
        default: true
        
      context-inputs:
        description: 'Include inputs context'
        type: boolean
        default: true
      
  
  repository_dispatch:
    inputs:
        context-github:
          description: 'Include github context'
          type: boolean
          default: true

        context-env:
          description: 'Include env context'
          type: boolean
          default: true

        context-job:
          description: 'Include job context'
          type: boolean
          default: true

        context-steps:
          description: 'Include steps context'
          type: boolean
          default: true

        context-runner:
          description: 'Include runner context'
          type: boolean
          default: true

        context-secrets:
          description: 'Include secrets context'
          type: boolean
          default: true

        context-strategy:
          description: 'Include strategy context'
          type: boolean
          default: true

        context-matrix:
          description: 'Include matrix context'
          type: boolean
          default: true

        context-inputs:
          description: 'Include inputs context'
          type: boolean
          default: true

jobs:
  display-selected-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: display-github-context
        if: github.event.client_payload.context-github == true || inputs.context-github == true
        run: echo '${{ toJSON(github) }}'
      
      - name: display-env-context
        if: github.event.client_payload.context-env == true || inputs.context-env == true
        run: echo '${{ toJSON(env) }}'
      
      - name: display-job-context
        if: github.event.client_payload.context-job == true || inputs.context-job == true
        run: echo '${{ toJSON(job) }}'
      
      - name: display-steps-context
        if: github.event.client_payload.context-steps == true || inputs.context-steps == true
        run: echo '${{ toJSON(steps) }}'
      
      - name: display-runner-context
        if: github.event.inputs.context-runner == true || inputs.context-runner == true
        run: echo '${{ toJSON(runner) }}'
      
      - name: display-secrets-context
        if: github.event.client_payload.context-secrets == true || inputs.context-secrets == true
        run: echo '${{ toJSON(secrets) }}'
      
      - name: display-strategy-context
        if: github.event.client_payload.context-strategy == true || inputs.context-strategy == true
        run: echo '${{ toJSON(strategy) }}'
      
      - name: display-matrix-context
        if: github.event.client_payload.context-matrix == true || inputs.context-matrix == true
        run: echo '${{ toJSON(matrix) }}'
      
      - name: display-inputs-context
        if: github.event.client_payload.context-inputs == true || inputs.context-inputs == true
        run: echo '${{ toJSON(inputs) }}'
