name: Check environment
on:
  workflow_dispatch:
jobs:
  dev-data:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Display dev data
        run: echo ${{ secrets.DEV_SECRET }}
  preprod-data:
    runs-on: ubuntu-latest
    environment: preprod
    steps:
      - name: Display preprod data
        run: echo ${{ secrets.PREPROD_SECRET }}
        
