name: Action 2
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths: 'frontend/**'
    
jobs:
  generate-test-report:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './frontend/base'
    outputs:
      data: ${{ steps.save-data.outputs.data }}
    env:
      COVERAGE_REPORT_NAME: coverage-report-${{ github.actor }}
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
    
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '18.x'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build application
        run: npm run build

      - name: Run linter
        run: npm run lint
    
      - name: Run tests and generate test report
        run: npm run test
      
      - name: Upload report artifact with 10 days of retention period
        id: upload-artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ env.COVERAGE_REPORT_NAME }}
          path: '**/test-results.json'
          retention-days: 10
          
      - name: Save report data to output
        id: save-data
        run: echo "data=$(cat frontend\base\coverage\test-results.json | jq)" >> $GITHUB_OUTPUT
      
  send-report-email:
    runs-on: ubuntu-latest
    needs: generate-test-report
    env:
      COVERAGE_REPORT_NAME: coverage-report-${{ github.actor }}
      BOSS_EMAIL: hubert.klonowski@predicagroup.com
      MESSAGE_SUBJECT: Test report by ${{ github.actor }}
    steps:
      - name: Download test report artifact
        id: download-artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: ${{ env.COVERAGE_REPORT_NAME }}
          paths: test-results.json
  
      - name: Send email to boss
        uses: devellany/send-mail@v1.0.2
        with:
          host: smtp.google.com
          account: ${{secrets.MAIL_ADDRESS}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: Bulbo Inc Test Center
          from: ${{secrets.MAIL_ADDRESS}}
          to: ${{ env.BOSS_EMAIL }}
          subject: ${{ env.MESSAGE_SUBJECT }}
          body: |
            We got it!!!!
            ${{ needs.generate-test-report.outputs.data }}
          contentType: text/html
