name: Cheeser user
on:
  workflow_dispatch:
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.6.0

      - uses: './.github/workflows/cheeser-action.yml'
        id: cheeser
        with:
          name: John
          API_KEY: key

      - name: Display output cheese
        run: echo "${{ steps.cheeser.OUTPUT }}"