name: Cheeser user
on:
  workflow_dispatch:
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
    
      - name: Get cheese
        id: cheese
        uses: ./.github/workflows/cheeser.yml
      
      - name: Display output cheese
        run: echo "${{ steps.cheese.OUTPUT }}"
