name: Cheeser user
on:
  workflow_dispatch:
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/cheeser/cheeser-action.yml
        name: cheeser
        id: cheeser
        with:
          name: John
          API_KEY: key
      
      - name: Display output cheese
        run: echo "${{ steps.cheeser.OUTPUT }}"
