name: Cheeser user
on:
  workflow_dispatch:
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
    
      - name: tree
        run: |
          cd .github
          tree
    
      - uses: ./.github/actions/cheeser
        name: cheeser
        id: cheeser
        with:
          name: John
          API_KEY: 'key'
      
      - name: Display output cheese
        run: echo "${{ steps.cheese.OUTPUT }}"
